///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationOpenImages
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationOpenImagesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("dc777239-6797-41e4-b2c0-6c666e646d61")]
    public partial class AutomationOpenImagesRepository : RepoGenBaseFolder
    {
        static AutomationOpenImagesRepository instance = new AutomationOpenImagesRepository();
        AutomationOpenImagesRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        AutomationOpenImagesRepositoryFolders.SNAPXAppFolder _snapx;
        RepoItemInfo _modeselectorburttonInfo;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationOpenImagesRepository element repository.
        /// </summary>
        [RepositoryFolder("dc777239-6797-41e4-b2c0-6c666e646d61")]
        public static AutomationOpenImagesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationOpenImagesRepository() 
            : base("AutomationOpenImagesRepository", "/", null, 0, false, "dc777239-6797-41e4-b2c0-6c666e646d61", ".\\RepositoryImages\\AutomationOpenImagesRepositorydc777239.rximgres")
        {
            _snapxuntitled = new AutomationOpenImagesRepositoryFolders.SnapXUntitledAppFolder(this);
            _snapx = new AutomationOpenImagesRepositoryFolders.SNAPXAppFolder(this);
            _modeselectorburttonInfo = new RepoItemInfo(this, "ModeSelectorBurtton", "/form[@title='Snap-X - [Untitled]']/container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59664']/container[@controlid='59648']/button[@text='Go']", 30000, null, "11f2337e-ac58-4f4e-9c35-55047285c28a");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dc777239-6797-41e4-b2c0-6c666e646d61")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ModeSelectorBurtton item.
        /// </summary>
        [RepositoryItem("11f2337e-ac58-4f4e-9c35-55047285c28a")]
        public virtual Ranorex.Button ModeSelectorBurtton
        {
            get
            {
                 return _modeselectorburttonInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ModeSelectorBurtton item info.
        /// </summary>
        [RepositoryItemInfo("11f2337e-ac58-4f4e-9c35-55047285c28a")]
        public virtual RepoItemInfo ModeSelectorBurttonInfo
        {
            get
            {
                return _modeselectorburttonInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
        public virtual AutomationOpenImagesRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The SNAPX folder.
        /// </summary>
        [RepositoryFolder("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
        public virtual AutomationOpenImagesRepositoryFolders.SNAPXAppFolder SNAPX
        {
            get { return _snapx; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class AutomationOpenImagesRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _textmeasureInfo;
            RepoItemInfo _openimagebuttonInfo;
            RepoItemInfo _featurefinderInfo;
            RepoItemInfo _crosshairbuttonInfo;
            RepoItemInfo _rightclicktoreachthegobuttonInfo;
            RepoItemInfo _switchtosensorInfo;
            RepoItemInfo _toolboxInfo;
            PicturesInfoClass _picturesInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "e3dfd10c-a895-4621-92a1-f5ebfd2043f6", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 30000, null, "7cae186e-6791-4520-a994-155995771fff");
                _textmeasureInfo = new RepoItemInfo(this, "TextMeasure", "container[@controlid='59648']/form[@title='Untitled']//text[@controlid='2394']", 30000, null, "a13ef2c4-6a00-4e6d-8581-81963f233d71");
                _openimagebuttonInfo = new RepoItemInfo(this, "OpenImageButton", "?/?/form[@title='Untitled']//toolbar[@controlid='59392']/button[@text='Open Image']", 30000, null, "95015fa7-8b5e-457e-b717-307eb061506c");
                _featurefinderInfo = new RepoItemInfo(this, "FeatureFinder", "container[@controlid='59648']/form[@title='Untitled']//toolbar[@class='ToolbarWindow32' and @instance='2']/button[@commandid='5064' and @checked='false']", 30000, null, "f18ab8eb-0cd7-4d29-92dd-d012ee0f9d6b");
                _crosshairbuttonInfo = new RepoItemInfo(this, "CrossHairButton", "container[@controlid='59648']/form[@title='Untitled']//toolbar[@class='ToolbarWindow32' and @instance='1']/button[@commandid='5009']", 30000, null, "1e26cba9-c6e1-4a6d-b493-621309387c68");
                _rightclicktoreachthegobuttonInfo = new RepoItemInfo(this, "RightClickToReachTheGoButton", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59664']/container[@controlid='59648']", 30000, null, "5de3b19f-84d2-454c-9ac2-f3a8871bc86d");
                _switchtosensorInfo = new RepoItemInfo(this, "SwitchToSensor", "container[@controlid='59648']/form[@title='Untitled']/?/?/element[@controlid='59650']/element[@controlid='59648']/toolbar[@controlid='59392']/button[@commandid='40029']", 30000, null, "d5923ba4-1c19-4432-8468-cddd7894ff41");
                _toolboxInfo = new RepoItemInfo(this, "Toolbox", "?/?/form[@title='Untitled' and @enabled='True']/?/?/tabpage[@title='Toolbox']", 30000, null, "8867a432-6080-4627-a766-cecd00c357fa");
                _picturesInfo = new PicturesInfoClass(this);
            }

            /// <summary>
            /// The PicturesInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f5c4d0cb-7674-425b-a28f-22fa4f492232")]
            public class PicturesInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PicturesInfoClass class constructor.
                /// </summary>
                public PicturesInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Pictures", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='233245920']/text[@controlid='110']", 30000, null, "f5c4d0cb-7674-425b-a28f-22fa4f492232")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("bfd88a1e-8471-4a5c-8118-9957174fcd78")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("bfd88a1e-8471-4a5c-8118-9957174fcd78");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("bfd88a1e-8471-4a5c-8118-9957174fcd78")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("bfd88a1e-8471-4a5c-8118-9957174fcd78", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("f00973a6-966f-43ed-87ce-28508d2f8d41")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("f00973a6-966f-43ed-87ce-28508d2f8d41");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f00973a6-966f-43ed-87ce-28508d2f8d41")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f00973a6-966f-43ed-87ce-28508d2f8d41", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("5a0edaa1-2ac7-40aa-a1c6-a1abc60a4028")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("5a0edaa1-2ac7-40aa-a1c6-a1abc60a4028");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5a0edaa1-2ac7-40aa-a1c6-a1abc60a4028")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5a0edaa1-2ac7-40aa-a1c6-a1abc60a4028", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("7034b7a7-4116-47c5-b45e-bbee31b314cd")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("7034b7a7-4116-47c5-b45e-bbee31b314cd");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7034b7a7-4116-47c5-b45e-bbee31b314cd")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7034b7a7-4116-47c5-b45e-bbee31b314cd", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <returns>The Screenshot5 image.</returns>
                [RepositoryImage("e50ee231-8646-4b8f-8d46-43108f13dd74")]
                public CompressedImage GetScreenshot5()
                {
                    return GetImage("e50ee231-8646-4b8f-8d46-43108f13dd74");
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e50ee231-8646-4b8f-8d46-43108f13dd74")]
                public CompressedImage GetScreenshot5(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e50ee231-8646-4b8f-8d46-43108f13dd74", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <returns>The Screenshot6 image.</returns>
                [RepositoryImage("eb79be23-9623-4c08-86b4-c2cfd5fbf8b8")]
                public CompressedImage GetScreenshot6()
                {
                    return GetImage("eb79be23-9623-4c08-86b4-c2cfd5fbf8b8");
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("eb79be23-9623-4c08-86b4-c2cfd5fbf8b8")]
                public CompressedImage GetScreenshot6(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("eb79be23-9623-4c08-86b4-c2cfd5fbf8b8", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot7 item image.
                /// </summary>
                /// <returns>The Screenshot7 image.</returns>
                [RepositoryImage("f7cf26d0-f616-4a2e-afc3-17f189cc8c09")]
                public CompressedImage GetScreenshot7()
                {
                    return GetImage("f7cf26d0-f616-4a2e-afc3-17f189cc8c09");
                }

                /// <summary>
                /// Gets the Screenshot7 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f7cf26d0-f616-4a2e-afc3-17f189cc8c09")]
                public CompressedImage GetScreenshot7(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f7cf26d0-f616-4a2e-afc3-17f189cc8c09", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("7cae186e-6791-4520-a994-155995771fff")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("7cae186e-6791-4520-a994-155995771fff")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The TextMeasure item.
            /// </summary>
            [RepositoryItem("a13ef2c4-6a00-4e6d-8581-81963f233d71")]
            public virtual Ranorex.Text TextMeasure
            {
                get
                {
                    return _textmeasureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextMeasure item info.
            /// </summary>
            [RepositoryItemInfo("a13ef2c4-6a00-4e6d-8581-81963f233d71")]
            public virtual RepoItemInfo TextMeasureInfo
            {
                get
                {
                    return _textmeasureInfo;
                }
            }

            /// <summary>
            /// The OpenImageButton item.
            /// </summary>
            [RepositoryItem("95015fa7-8b5e-457e-b717-307eb061506c")]
            public virtual Ranorex.Button OpenImageButton
            {
                get
                {
                    return _openimagebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenImageButton item info.
            /// </summary>
            [RepositoryItemInfo("95015fa7-8b5e-457e-b717-307eb061506c")]
            public virtual RepoItemInfo OpenImageButtonInfo
            {
                get
                {
                    return _openimagebuttonInfo;
                }
            }

            /// <summary>
            /// The FeatureFinder item.
            /// </summary>
            [RepositoryItem("f18ab8eb-0cd7-4d29-92dd-d012ee0f9d6b")]
            public virtual Ranorex.Button FeatureFinder
            {
                get
                {
                    return _featurefinderInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FeatureFinder item info.
            /// </summary>
            [RepositoryItemInfo("f18ab8eb-0cd7-4d29-92dd-d012ee0f9d6b")]
            public virtual RepoItemInfo FeatureFinderInfo
            {
                get
                {
                    return _featurefinderInfo;
                }
            }

            /// <summary>
            /// The CrossHairButton item.
            /// </summary>
            [RepositoryItem("1e26cba9-c6e1-4a6d-b493-621309387c68")]
            public virtual Ranorex.Button CrossHairButton
            {
                get
                {
                    return _crosshairbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CrossHairButton item info.
            /// </summary>
            [RepositoryItemInfo("1e26cba9-c6e1-4a6d-b493-621309387c68")]
            public virtual RepoItemInfo CrossHairButtonInfo
            {
                get
                {
                    return _crosshairbuttonInfo;
                }
            }

            /// <summary>
            /// The RightClickToReachTheGoButton item.
            /// </summary>
            [RepositoryItem("5de3b19f-84d2-454c-9ac2-f3a8871bc86d")]
            public virtual Ranorex.Container RightClickToReachTheGoButton
            {
                get
                {
                    return _rightclicktoreachthegobuttonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RightClickToReachTheGoButton item info.
            /// </summary>
            [RepositoryItemInfo("5de3b19f-84d2-454c-9ac2-f3a8871bc86d")]
            public virtual RepoItemInfo RightClickToReachTheGoButtonInfo
            {
                get
                {
                    return _rightclicktoreachthegobuttonInfo;
                }
            }

            /// <summary>
            /// The SwitchToSensor item.
            /// </summary>
            [RepositoryItem("d5923ba4-1c19-4432-8468-cddd7894ff41")]
            public virtual Ranorex.Button SwitchToSensor
            {
                get
                {
                    return _switchtosensorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchToSensor item info.
            /// </summary>
            [RepositoryItemInfo("d5923ba4-1c19-4432-8468-cddd7894ff41")]
            public virtual RepoItemInfo SwitchToSensorInfo
            {
                get
                {
                    return _switchtosensorInfo;
                }
            }

            /// <summary>
            /// The Toolbox item.
            /// </summary>
            [RepositoryItem("8867a432-6080-4627-a766-cecd00c357fa")]
            public virtual Ranorex.TabPage Toolbox
            {
                get
                {
                    return _toolboxInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Toolbox item info.
            /// </summary>
            [RepositoryItemInfo("8867a432-6080-4627-a766-cecd00c357fa")]
            public virtual RepoItemInfo ToolboxInfo
            {
                get
                {
                    return _toolboxInfo;
                }
            }

            /// <summary>
            /// The Pictures item.
            /// </summary>
            [RepositoryItem("f5c4d0cb-7674-425b-a28f-22fa4f492232")]
            public virtual Ranorex.Text Pictures
            {
                get
                {
                    return _picturesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Pictures item info.
            /// </summary>
            [RepositoryItemInfo("f5c4d0cb-7674-425b-a28f-22fa4f492232")]
            public virtual PicturesInfoClass PicturesInfo
            {
                get
                {
                    return _picturesInfo;
                }
            }
        }

        /// <summary>
        /// The SNAPXAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
        public partial class SNAPXAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _modeselectorInfo;

            /// <summary>
            /// Creates a new SNAPX  folder.
            /// </summary>
            public SNAPXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SNAPX", "/contextmenu[@processname='SNAP-X']", parentFolder, 30000, null, false, "2b41fb7f-d86f-4409-af73-29af0ee78d38", "")
            {
                _modeselectorInfo = new RepoItemInfo(this, "ModeSelector", "?/?/menuitem[@accessiblename='Mode Selector']", 30000, null, "5adda42f-f2ed-4dfc-a90a-4a9051fd79b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ModeSelector item.
            /// </summary>
            [RepositoryItem("5adda42f-f2ed-4dfc-a90a-4a9051fd79b8")]
            public virtual Ranorex.MenuItem ModeSelector
            {
                get
                {
                    return _modeselectorInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ModeSelector item info.
            /// </summary>
            [RepositoryItemInfo("5adda42f-f2ed-4dfc-a90a-4a9051fd79b8")]
            public virtual RepoItemInfo ModeSelectorInfo
            {
                get
                {
                    return _modeselectorInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}