///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationOpenImages
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationOpenImagesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("dc777239-6797-41e4-b2c0-6c666e646d61")]
    public partial class AutomationOpenImagesRepository : RepoGenBaseFolder
    {
        static AutomationOpenImagesRepository instance = new AutomationOpenImagesRepository();
        AutomationOpenImagesRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        AutomationOpenImagesRepositoryFolders.SNAPXAppFolder _snapx;
        RepoItemInfo _modeselectorburttonInfo;
        RepoItemInfo _printInfo;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationOpenImagesRepository element repository.
        /// </summary>
        [RepositoryFolder("dc777239-6797-41e4-b2c0-6c666e646d61")]
        public static AutomationOpenImagesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationOpenImagesRepository() 
            : base("AutomationOpenImagesRepository", "/", null, 0, false, "dc777239-6797-41e4-b2c0-6c666e646d61", ".\\RepositoryImages\\AutomationOpenImagesRepositorydc777239.rximgres")
        {
            _snapxuntitled = new AutomationOpenImagesRepositoryFolders.SnapXUntitledAppFolder(this);
            _snapx = new AutomationOpenImagesRepositoryFolders.SNAPXAppFolder(this);
            _modeselectorburttonInfo = new RepoItemInfo(this, "ModeSelectorBurtton", "/form[@title='Snap-X - [Untitled]']/container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59664']/container[@controlid='59648']/button[@text='Go']", 30000, null, "11f2337e-ac58-4f4e-9c35-55047285c28a");
            _printInfo = new RepoItemInfo(this, "Print", "/form[@title='Snap-X - [Untitled]']/?/?/form[@title='Untitled']/?/?/tabpage[@title='Print']", 30000, null, "f428d2c0-104a-4789-bdbe-40f54a802f8b");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dc777239-6797-41e4-b2c0-6c666e646d61")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ModeSelectorBurtton item.
        /// </summary>
        [RepositoryItem("11f2337e-ac58-4f4e-9c35-55047285c28a")]
        public virtual Ranorex.Button ModeSelectorBurtton
        {
            get
            {
                 return _modeselectorburttonInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ModeSelectorBurtton item info.
        /// </summary>
        [RepositoryItemInfo("11f2337e-ac58-4f4e-9c35-55047285c28a")]
        public virtual RepoItemInfo ModeSelectorBurttonInfo
        {
            get
            {
                return _modeselectorburttonInfo;
            }
        }

        /// <summary>
        /// The Print item.
        /// </summary>
        [RepositoryItem("f428d2c0-104a-4789-bdbe-40f54a802f8b")]
        public virtual Ranorex.TabPage Print
        {
            get
            {
                 return _printInfo.CreateAdapter<Ranorex.TabPage>(true);
            }
        }

        /// <summary>
        /// The Print item info.
        /// </summary>
        [RepositoryItemInfo("f428d2c0-104a-4789-bdbe-40f54a802f8b")]
        public virtual RepoItemInfo PrintInfo
        {
            get
            {
                return _printInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
        public virtual AutomationOpenImagesRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The SNAPX folder.
        /// </summary>
        [RepositoryFolder("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
        public virtual AutomationOpenImagesRepositoryFolders.SNAPXAppFolder SNAPX
        {
            get { return _snapx; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class AutomationOpenImagesRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _textmeasureInfo;
            RepoItemInfo _openimagebuttonInfo;
            RepoItemInfo _featurefinderInfo;
            PicturesInfoClass _picturesInfo;
            RepoItemInfo _crosshairbuttonInfo;
            RepoItemInfo _rightclicktoreachthegobuttonInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "e3dfd10c-a895-4621-92a1-f5ebfd2043f6", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 30000, null, "7cae186e-6791-4520-a994-155995771fff");
                _textmeasureInfo = new RepoItemInfo(this, "TextMeasure", "container[@controlid='59648']/form[@title='Untitled']//text[@controlid='2394']", 30000, null, "a13ef2c4-6a00-4e6d-8581-81963f233d71");
                _openimagebuttonInfo = new RepoItemInfo(this, "OpenImageButton", "?/?/form[@title='Untitled']//toolbar[@controlid='59392']/button[@text='Open Image']", 30000, null, "95015fa7-8b5e-457e-b717-307eb061506c");
                _featurefinderInfo = new RepoItemInfo(this, "FeatureFinder", "container[@controlid='59648']/form[@title='Untitled']//toolbar[@class='ToolbarWindow32' and @instance='2']/button[@commandid='5064' and @checked='false']", 30000, null, "f18ab8eb-0cd7-4d29-92dd-d012ee0f9d6b");
                _picturesInfo = new PicturesInfoClass(this);
                _crosshairbuttonInfo = new RepoItemInfo(this, "CrossHairButton", "container[@controlid='59648']/form[@title='Untitled']//toolbar[@class='ToolbarWindow32' and @instance='1']/button[@commandid='5009']", 30000, null, "1e26cba9-c6e1-4a6d-b493-621309387c68");
                _rightclicktoreachthegobuttonInfo = new RepoItemInfo(this, "RightClickToReachTheGoButton", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59664']/container[@controlid='59648']", 30000, null, "5de3b19f-84d2-454c-9ac2-f3a8871bc86d");
            }

            /// <summary>
            /// The PicturesInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("6eb375ab-fee3-4ac5-bc46-a9c9a335c05f")]
            public class PicturesInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PicturesInfoClass class constructor.
                /// </summary>
                public PicturesInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Pictures", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='217744136']/text[@controlid='110']", 30000, null, "6eb375ab-fee3-4ac5-bc46-a9c9a335c05f")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("201784b1-1614-4261-b9a6-d7546a8efc33")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("201784b1-1614-4261-b9a6-d7546a8efc33");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("201784b1-1614-4261-b9a6-d7546a8efc33")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("201784b1-1614-4261-b9a6-d7546a8efc33", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("ffb8e0d2-11bf-4144-8d1a-f5b1c52847cc")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("ffb8e0d2-11bf-4144-8d1a-f5b1c52847cc");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ffb8e0d2-11bf-4144-8d1a-f5b1c52847cc")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ffb8e0d2-11bf-4144-8d1a-f5b1c52847cc", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("93fc80c2-dab7-499d-aa12-1bad3200e36a")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("93fc80c2-dab7-499d-aa12-1bad3200e36a");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("93fc80c2-dab7-499d-aa12-1bad3200e36a")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("93fc80c2-dab7-499d-aa12-1bad3200e36a", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("85e7b6e2-28e2-48d1-b73b-1178d0d2e880")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("85e7b6e2-28e2-48d1-b73b-1178d0d2e880");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("85e7b6e2-28e2-48d1-b73b-1178d0d2e880")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("85e7b6e2-28e2-48d1-b73b-1178d0d2e880", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <returns>The Screenshot5 image.</returns>
                [RepositoryImage("bbbae4cd-ce51-46f5-8f99-341e4b44405a")]
                public CompressedImage GetScreenshot5()
                {
                    return GetImage("bbbae4cd-ce51-46f5-8f99-341e4b44405a");
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("bbbae4cd-ce51-46f5-8f99-341e4b44405a")]
                public CompressedImage GetScreenshot5(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("bbbae4cd-ce51-46f5-8f99-341e4b44405a", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <returns>The Screenshot6 image.</returns>
                [RepositoryImage("140049e7-2a24-4c93-abcf-60d36a585c26")]
                public CompressedImage GetScreenshot6()
                {
                    return GetImage("140049e7-2a24-4c93-abcf-60d36a585c26");
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("140049e7-2a24-4c93-abcf-60d36a585c26")]
                public CompressedImage GetScreenshot6(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("140049e7-2a24-4c93-abcf-60d36a585c26", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot7 item image.
                /// </summary>
                /// <returns>The Screenshot7 image.</returns>
                [RepositoryImage("e6b9ed05-87be-4821-bc68-91d69d38f465")]
                public CompressedImage GetScreenshot7()
                {
                    return GetImage("e6b9ed05-87be-4821-bc68-91d69d38f465");
                }

                /// <summary>
                /// Gets the Screenshot7 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e6b9ed05-87be-4821-bc68-91d69d38f465")]
                public CompressedImage GetScreenshot7(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e6b9ed05-87be-4821-bc68-91d69d38f465", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3dfd10c-a895-4621-92a1-f5ebfd2043f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("7cae186e-6791-4520-a994-155995771fff")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("7cae186e-6791-4520-a994-155995771fff")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The TextMeasure item.
            /// </summary>
            [RepositoryItem("a13ef2c4-6a00-4e6d-8581-81963f233d71")]
            public virtual Ranorex.Text TextMeasure
            {
                get
                {
                    return _textmeasureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextMeasure item info.
            /// </summary>
            [RepositoryItemInfo("a13ef2c4-6a00-4e6d-8581-81963f233d71")]
            public virtual RepoItemInfo TextMeasureInfo
            {
                get
                {
                    return _textmeasureInfo;
                }
            }

            /// <summary>
            /// The OpenImageButton item.
            /// </summary>
            [RepositoryItem("95015fa7-8b5e-457e-b717-307eb061506c")]
            public virtual Ranorex.Button OpenImageButton
            {
                get
                {
                    return _openimagebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenImageButton item info.
            /// </summary>
            [RepositoryItemInfo("95015fa7-8b5e-457e-b717-307eb061506c")]
            public virtual RepoItemInfo OpenImageButtonInfo
            {
                get
                {
                    return _openimagebuttonInfo;
                }
            }

            /// <summary>
            /// The FeatureFinder item.
            /// </summary>
            [RepositoryItem("f18ab8eb-0cd7-4d29-92dd-d012ee0f9d6b")]
            public virtual Ranorex.Button FeatureFinder
            {
                get
                {
                    return _featurefinderInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FeatureFinder item info.
            /// </summary>
            [RepositoryItemInfo("f18ab8eb-0cd7-4d29-92dd-d012ee0f9d6b")]
            public virtual RepoItemInfo FeatureFinderInfo
            {
                get
                {
                    return _featurefinderInfo;
                }
            }

            /// <summary>
            /// The Pictures item.
            /// </summary>
            [RepositoryItem("6eb375ab-fee3-4ac5-bc46-a9c9a335c05f")]
            public virtual Ranorex.Text Pictures
            {
                get
                {
                    return _picturesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Pictures item info.
            /// </summary>
            [RepositoryItemInfo("6eb375ab-fee3-4ac5-bc46-a9c9a335c05f")]
            public virtual PicturesInfoClass PicturesInfo
            {
                get
                {
                    return _picturesInfo;
                }
            }

            /// <summary>
            /// The CrossHairButton item.
            /// </summary>
            [RepositoryItem("1e26cba9-c6e1-4a6d-b493-621309387c68")]
            public virtual Ranorex.Button CrossHairButton
            {
                get
                {
                    return _crosshairbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CrossHairButton item info.
            /// </summary>
            [RepositoryItemInfo("1e26cba9-c6e1-4a6d-b493-621309387c68")]
            public virtual RepoItemInfo CrossHairButtonInfo
            {
                get
                {
                    return _crosshairbuttonInfo;
                }
            }

            /// <summary>
            /// The RightClickToReachTheGoButton item.
            /// </summary>
            [RepositoryItem("5de3b19f-84d2-454c-9ac2-f3a8871bc86d")]
            public virtual Ranorex.Container RightClickToReachTheGoButton
            {
                get
                {
                    return _rightclicktoreachthegobuttonInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RightClickToReachTheGoButton item info.
            /// </summary>
            [RepositoryItemInfo("5de3b19f-84d2-454c-9ac2-f3a8871bc86d")]
            public virtual RepoItemInfo RightClickToReachTheGoButtonInfo
            {
                get
                {
                    return _rightclicktoreachthegobuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SNAPXAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
        public partial class SNAPXAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _modeselectorInfo;

            /// <summary>
            /// Creates a new SNAPX  folder.
            /// </summary>
            public SNAPXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SNAPX", "/contextmenu[@processname='SNAP-X']", parentFolder, 30000, null, false, "2b41fb7f-d86f-4409-af73-29af0ee78d38", "")
            {
                _modeselectorInfo = new RepoItemInfo(this, "ModeSelector", "?/?/menuitem[@accessiblename='Mode Selector']", 30000, null, "5adda42f-f2ed-4dfc-a90a-4a9051fd79b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b41fb7f-d86f-4409-af73-29af0ee78d38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ModeSelector item.
            /// </summary>
            [RepositoryItem("5adda42f-f2ed-4dfc-a90a-4a9051fd79b8")]
            public virtual Ranorex.MenuItem ModeSelector
            {
                get
                {
                    return _modeselectorInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ModeSelector item info.
            /// </summary>
            [RepositoryItemInfo("5adda42f-f2ed-4dfc-a90a-4a9051fd79b8")]
            public virtual RepoItemInfo ModeSelectorInfo
            {
                get
                {
                    return _modeselectorInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}